import { boolean, integer, pgEnum, pgTable, serial, text, timestamp, varchar } from "drizzle-orm/pg-core";

export const roleEnum = pgEnum("role", ["user", "admin"]);
export const registrationStatusEnum = pgEnum("registration_status", ["PENDING", "ACCEPTED", "REJECTED"]);
export const emailTemplateCategoryEnum = pgEnum("email_template_category", ["ACCEPTANCE", "GENERAL"]);
export const emailMediaPlacementEnum = pgEnum("email_media_placement", ["INLINE", "ATTACHMENT"]);
export const emailLogStatusEnum = pgEnum("email_log_status", ["PENDING", "SENDING", "SENT", "FAILED"]);

export const users = pgTable("users", {
  id: serial("id").primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), passwordHash: text("passwordHash"), loginMethod: varchar("loginMethod", { length: 64 }).default("local"), role: roleEnum("role").default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const registrations = pgTable("registrations", {
  id: serial("id").primaryKey(), firstName: varchar("firstName", { length: 120 }).notNull(), lastName: varchar("lastName", { length: 120 }).notNull(), country: varchar("country", { length: 80 }).notNull(), countryCode: varchar("countryCode", { length: 8 }).notNull(), whatsappNumber: varchar("whatsappNumber", { length: 40 }).notNull(), normalizedWhatsapp: varchar("normalizedWhatsapp", { length: 40 }).notNull().unique(), classLevel: varchar("classLevel", { length: 120 }).notNull(), school: varchar("school", { length: 240 }).notNull(), email: varchar("email", { length: 320 }).notNull().unique(), status: registrationStatusEnum("status").default("PENDING").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull(), reviewedAt: timestamp("reviewedAt"), reviewedBy: integer("reviewedBy"), rejectionReason: text("rejectionReason"),
});
export const adminInvites = pgTable("adminInvites", { id: serial("id").primaryKey(), tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), expiresAt: timestamp("expiresAt").notNull(), usedAt: timestamp("usedAt"), usedBy: integer("usedBy"), revokedAt: timestamp("revokedAt") });
export const emailConfig = pgTable("emailConfig", { id: serial("id").primaryKey(), senderName: varchar("senderName", { length: 160 }).notNull(), senderEmail: varchar("senderEmail", { length: 320 }).notNull(), replyTo: varchar("replyTo", { length: 320 }), gmailClientIdEncrypted: text("gmailClientIdEncrypted"), gmailClientSecretEncrypted: text("gmailClientSecretEncrypted"), gmailRefreshTokenEncrypted: text("gmailRefreshTokenEncrypted"), enabled: boolean("enabled").notNull().default(false), updatedBy: integer("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const emailTemplates = pgTable("emailTemplates", { id: serial("id").primaryKey(), category: emailTemplateCategoryEnum("category").default("ACCEPTANCE").notNull(), subject: varchar("subject", { length: 240 }).notNull(), body: text("body").notNull(), htmlBody: text("htmlBody"), groupLink: varchar("groupLink", { length: 500 }), channelLink: varchar("channelLink", { length: 500 }), updatedBy: integer("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const emailMedia = pgTable("emailMedia", { id: serial("id").primaryKey(), templateId: integer("templateId"), fileKey: varchar("fileKey", { length: 500 }).notNull(), fileUrl: varchar("fileUrl", { length: 700 }).notNull(), filename: varchar("filename", { length: 240 }).notNull(), mimeType: varchar("mimeType", { length: 120 }).notNull(), contentId: varchar("contentId", { length: 120 }), placement: emailMediaPlacementEnum("placement").notNull(), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const emailLogs = pgTable("emailLogs", { id: serial("id").primaryKey(), recipient: varchar("recipient", { length: 320 }).notNull(), emailType: varchar("emailType", { length: 80 }).notNull(), subject: varchar("subject", { length: 240 }), registrationId: integer("registrationId"), status: emailLogStatusEnum("status").notNull(), failureReason: text("failureReason"), providerMessageId: varchar("providerMessageId", { length: 240 }), idempotencyKey: varchar("idempotencyKey", { length: 200 }), retryOf: integer("retryOf"), sentBy: integer("sentBy"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const notifications = pgTable("notifications", { id: serial("id").primaryKey(), title: varchar("title", { length: 160 }).notNull(), body: text("body").notNull(), registrationId: integer("registrationId"), createdAt: timestamp("createdAt").defaultNow().notNull(), readAt: timestamp("readAt") });
export const notificationPreferences = pgTable("notificationPreferences", { id: serial("id").primaryKey(), masterEnabled: boolean("masterEnabled").notNull().default(true), newRegistration: boolean("newRegistration").notNull().default(true), emailFailure: boolean("emailFailure").notNull().default(true), adminEvents: boolean("adminEvents").notNull().default(true), updatedBy: integer("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const auditLogs = pgTable("auditLogs", { id: serial("id").primaryKey(), action: varchar("action", { length: 160 }).notNull(), adminId: integer("adminId").notNull(), registrationId: integer("registrationId"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Registration = typeof registrations.$inferSelect; export type InsertRegistration = typeof registrations.$inferInsert;
