import crypto from "node:crypto";
import { and, desc, eq, gt, isNull, like, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { adminInvites, auditLogs, emailConfig, emailLogs, emailMedia, emailTemplates, InsertUser, notificationPreferences, notifications, registrations, users } from "../drizzle/schema.js";
import { ENV } from './_core/env.js';
import { DEFAULT_BODY, DEFAULT_HTML, decryptProviderKey } from "./email.js";
let _db: ReturnType<typeof drizzle> | null = null;
// `prepare: false` is required when connecting through Supabase's Supavisor
// transaction-mode pooler (the 6543 connection string) — that pooler does
// not support prepared statements. Harmless against the direct/session
// connection string too, so it's left on unconditionally.
export async function getDb(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL;if(!_db&&url){try{_db=drizzle(postgres(url,{prepare:false,ssl:"require"}))}catch{_db=null}}return _db}
export async function upsertUser(user:InsertUser){const db=await getDb();if(!db||!user.openId)return;const values:InsertUser={openId:user.openId,name:user.name??null,email:user.email??null,loginMethod:user.loginMethod??null,lastSignedIn:user.lastSignedIn??new Date()};const updateSet:any={name:values.name,email:values.email,loginMethod:values.loginMethod,lastSignedIn:values.lastSignedIn};if(user.role){values.role=user.role;updateSet.role=user.role}else if(user.openId===ENV.ownerOpenId){values.role="admin";updateSet.role="admin"}await db.insert(users).values(values).onConflictDoUpdate({target:users.openId,set:updateSet})}
export async function getUserByOpenId(openId:string){const db=await getDb();if(!db)return;const rows=await db.select().from(users).where(eq(users.openId,openId)).limit(1);return rows[0]}
export async function getUserByEmail(email:string){const db=await getDb();if(!db)return;const rows=await db.select().from(users).where(eq(users.email,email)).limit(1);return rows[0]}
export async function countUsers(){const db=await getDb();if(!db)return 0;const rows=await db.select({id:users.id}).from(users);return rows.length}
export async function linkGoogleUser(id:number, openId:string, name:string, email:string, role:"admin"|"user"){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.update(users).set({openId,name,email,loginMethod:"google",role,lastSignedIn:new Date()}).where(eq(users.id,id))}
export async function listRegistrations(filter?:{status?:"PENDING"|"ACCEPTED"|"REJECTED";search?:string}){const db=await getDb();if(!db)return[];const conditions:any[]=[];if(filter?.status)conditions.push(eq(registrations.status,filter.status));if(filter?.search){const s=`%${filter.search}%`;conditions.push(or(like(registrations.firstName,s),like(registrations.lastName,s),like(registrations.email,s),like(registrations.school,s),like(registrations.normalizedWhatsapp,s)))}return db.select().from(registrations).where(conditions.length?and(...conditions):undefined).orderBy(desc(registrations.createdAt)).limit(250)}
export async function getRegistration(id:number){const db=await getDb();if(!db)return;const rows=await db.select().from(registrations).where(eq(registrations.id,id)).limit(1);return rows[0]}
export async function deleteRegistration(id:number){const db=await getDb();if(!db)return false;const existing=await getRegistration(id);if(!existing)return false;await db.transaction(async tx=>{await tx.delete(emailLogs).where(eq(emailLogs.registrationId,id));await tx.delete(notifications).where(eq(notifications.registrationId,id));await tx.delete(auditLogs).where(eq(auditLogs.registrationId,id));await tx.delete(registrations).where(eq(registrations.id,id));});return true}
export async function getStats(){const db=await getDb();if(!db)return{total:0,pending:0,accepted:0,rejected:0,today:0,week:0,month:0,byCountry:[],byClass:[],bySchool:[]};const rows=await db.select().from(registrations);const now=Date.now(),day=86400000;const group=(key:"country"|"classLevel"|"school")=>Object.entries(rows.reduce<Record<string,number>>((a,r)=>{a[r[key]]=(a[r[key]]||0)+1;return a},{})).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,8);return{total:rows.length,pending:rows.filter(r=>r.status==="PENDING").length,accepted:rows.filter(r=>r.status==="ACCEPTED").length,rejected:rows.filter(r=>r.status==="REJECTED").length,today:rows.filter(r=>now-r.createdAt.getTime()<day).length,week:rows.filter(r=>now-r.createdAt.getTime()<day*7).length,month:rows.filter(r=>now-r.createdAt.getTime()<day*30).length,byCountry:group("country"),byClass:group("classLevel"),bySchool:group("school")}}
export async function getConfig(){const db=await getDb();if(!db)return;const configs=await db.select().from(emailConfig).limit(1);const templates=await db.select().from(emailTemplates).orderBy(desc(emailTemplates.updatedAt));const prefs=await db.select().from(notificationPreferences).limit(1);return{config:configs[0],template:templates.find(t=>t.category==="ACCEPTANCE"),generalTemplate:templates.find(t=>t.category==="GENERAL"),preferences:prefs[0]}}
export async function ensureDefaults(){const db=await getDb();if(!db)return;const templates=await db.select().from(emailTemplates).limit(1);if(!templates.length)await db.insert(emailTemplates).values({category:"ACCEPTANCE",subject:"🎉 You're in — THE NEXT MIND",body:DEFAULT_BODY,htmlBody:DEFAULT_HTML(DEFAULT_BODY.replace(/\n{2,}/g,"<br><br>").replace(/\n/g,"<br>")),groupLink:"https://chat.whatsapp.com/JCX4hLJol0sDbzH4PpJGms?s=cl&p=a&mlu=4&ilr=4",channelLink:"https://whatsapp.com/channel/0029VbD8HWH6mYPIo9ONqD1c"});const seeded=await db.select().from(emailTemplates).where(eq(emailTemplates.category,"ACCEPTANCE")).limit(1);if(seeded[0]&&!seeded[0].body)await db.update(emailTemplates).set({subject:"🎉 You're in — THE NEXT MIND",body:DEFAULT_BODY,htmlBody:DEFAULT_HTML(DEFAULT_BODY.replace(/\n{2,}/g,"<br><br>").replace(/\n/g,"<br>")),groupLink:"https://chat.whatsapp.com/JCX4hLJol0sDbzH4PpJGms?s=cl&p=a&mlu=4&ilr=4",channelLink:"https://whatsapp.com/channel/0029VbD8HWH6mYPIo9ONqD1c"}).where(eq(emailTemplates.id,seeded[0].id));const prefs=await db.select().from(notificationPreferences).limit(1);if(!prefs.length)await db.insert(notificationPreferences).values({masterEnabled:true,newRegistration:true,emailFailure:true,adminEvents:true})}
export async function createAudit(action:string,adminId:number,registrationId?:number){const db=await getDb();if(db)await db.insert(auditLogs).values({action,adminId,registrationId})}
export async function createNotification(title:string,body:string,registrationId?:number,kind:"newRegistration"|"emailFailure"|"adminEvents"="adminEvents"){const db=await getDb();if(!db)return;const rows=await db.select().from(notificationPreferences).limit(1);const p=rows[0];if(p&&!p.masterEnabled)return;if(p&&kind==="newRegistration"&&!p.newRegistration)return;if(p&&kind==="emailFailure"&&!p.emailFailure)return;if(p&&kind==="adminEvents"&&!p.adminEvents)return;await db.insert(notifications).values({title,body,registrationId})}
export async function createEmailLog(values:any){const db=await getDb();if(db)return db.insert(emailLogs).values(values)}
export async function updateEmailLog(id:number,values:any){const db=await getDb();if(db)await db.update(emailLogs).set(values).where(eq(emailLogs.id,id))}
export async function getEmailMedia(templateId?:number){const db=await getDb();if(!db)return[];return db.select().from(emailMedia).where(templateId?eq(emailMedia.templateId,templateId):undefined).orderBy(emailMedia.createdAt)}

export async function createLocalUser(values:{openId:string;name:string;email:string;passwordHash:string;role?:"user"|"admin"}){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.insert(users).values({...values,loginMethod:"local"});const rows=await db.select().from(users).where(eq(users.openId,values.openId)).limit(1);if(!rows[0])throw new Error("Unable to create user");return rows[0]}
export async function deleteUser(id:number){const db=await getDb();if(db)await db.delete(users).where(eq(users.id,id))}
export async function touchUser(id:number){const db=await getDb();if(db)await db.update(users).set({lastSignedIn:new Date()}).where(eq(users.id,id))}
export async function updateLocalAccount(id:number,values:{name?:string;email?:string;passwordHash?:string}){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.update(users).set(values).where(eq(users.id,id));const rows=await db.select().from(users).where(eq(users.id,id)).limit(1);return rows[0]}
export async function consumeAdminInvite(token:string,userId:number){const db=await getDb();if(!db)return false;const tokenHash=crypto.createHash("sha256").update(token).digest("hex");const rows=await db.select().from(adminInvites).where(and(eq(adminInvites.tokenHash,tokenHash),isNull(adminInvites.usedAt),isNull(adminInvites.revokedAt),gt(adminInvites.expiresAt,new Date()))).limit(1);if(!rows[0])return false;await db.update(adminInvites).set({usedAt:new Date(),usedBy:userId}).where(eq(adminInvites.id,rows[0].id));await db.update(users).set({role:"admin"}).where(eq(users.id,userId));return true}
