import crypto from "node:crypto";
import { and, desc, eq, gt, isNull, inArray, ne, or, like } from "drizzle-orm";
import { z } from "zod";
import { getCountries, getCountryCallingCode } from "libphonenumber-js";
import { COOKIE_NAME } from "../shared/const.js";
import { getSessionCookieOptions } from "./_core/cookies.js";
import { systemRouter } from "./_core/systemRouter.js";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc.js";
import { createAudit, createEmailLog, createNotification, deleteRegistration, ensureDefaults, getConfig, getDb, getEmailMedia, getRegistration, getStats, listRegistrations, updateEmailLog, updateLocalAccount } from "./db.js";
import { DEFAULT_BODY, DEFAULT_HTML, DEFAULT_SUBJECT, renderTemplate, sendEmail, textToEmailHtml } from "./email.js";
import { hashPassword, verifyPassword } from "./local-auth.js";
import { ENV } from "./_core/env.js";
import { adminInvites, emailConfig, emailLogs, emailMedia, emailTemplates, notificationPreferences, notifications, registrations, users } from "../drizzle/schema.js";
import { storagePut } from "./storage.js";

const tailoredLevels: Record<string, string[]> = { Nigeria: ["JSS 1", "JSS 2", "JSS 3", "SS 1", "SS 2", "SS 3", "University / undergraduate", "Graduate / postgraduate"], Ghana: ["Basic 7", "Basic 8", "Basic 9", "SHS 1", "SHS 2", "SHS 3", "University / undergraduate", "Graduate / postgraduate"], "United Kingdom": ["Year 7", "Year 8", "Year 9", "Year 10", "Year 11", "Sixth Form", "University / undergraduate", "Graduate / postgraduate"], "United States": ["Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12", "University / undergraduate", "Graduate / postgraduate"] };
const genericLevels = ["Middle school", "High school", "University / undergraduate", "Graduate / postgraduate", "Apprentice / vocational", "Other"];
const displayNames = new Intl.DisplayNames(["en"], { type: "region" });
const flagFor = (code: string) => code.replace(/./g, char => String.fromCodePoint(char.charCodeAt(0) + 127397));
const countries = getCountries().map(code => ({ name: displayNames.of(code) || code, isoCode: code, code: `+${getCountryCallingCode(code)}`, flag: flagFor(code) })).filter((country, index, list) => list.findIndex(item => item.name === country.name && item.code === country.code) === index).sort((a, b) => a.name.localeCompare(b.name));
const levels: Record<string, string[]> = Object.fromEntries(countries.map(country => [country.name, tailoredLevels[country.name] ?? genericLevels]));
const ACCEPTANCE_DEFAULT: { id?: number; category: "ACCEPTANCE"; subject: string; body: string; htmlBody: string; groupLink: string; channelLink: string } = { category: "ACCEPTANCE" as const, subject: DEFAULT_SUBJECT, body: DEFAULT_BODY, htmlBody: DEFAULT_HTML(textToEmailHtml(DEFAULT_BODY.replace("{{groupLink}}", "https://chat.whatsapp.com/JCX4hLJol0sDbzH4PpJGms?s=cl&p=a&mlu=4&ilr=4").replace("{{channelLink}}", "https://whatsapp.com/channel/0029VbD8HWH6mYPIo9ONqD1c"))), groupLink: "https://chat.whatsapp.com/JCX4hLJol0sDbzH4PpJGms?s=cl&p=a&mlu=4&ilr=4", channelLink: "https://whatsapp.com/channel/0029VbD8HWH6mYPIo9ONqD1c" };
const emailCategory = z.enum(["ACCEPTANCE", "GENERAL"]);
const adminOnly = adminProcedure;

function htmlForTemplate(template: { body: string; htmlBody?: string | null; groupLink?: string | null; channelLink?: string | null }, values: Record<string, string | undefined>) {
  const body = renderTemplate(template.body || "", { ...values, groupLink: template.groupLink ?? "", channelLink: template.channelLink ?? "" });
  const html = template.htmlBody ? renderTemplate(template.htmlBody, { ...values, groupLink: template.groupLink ?? "", channelLink: template.channelLink ?? "" }) : DEFAULT_HTML(textToEmailHtml(body));
  return { body, html };
}
async function sendConfiguredEmail(input: { category: string; recipient: string; subject: string; body: string; html: string; adminId?: number; registrationId?: number; media?: Array<{ fileUrl: string; filename: string; mimeType: string; contentId?: string | null; placement: "INLINE" | "ATTACHMENT" }>; retryOf?: number }) {
  const config = (await getConfig())?.config;
  const db = await getDb();
  const from = config ? `${config.senderName} <${config.senderEmail}>` : "";
  if (!db) return { ok: false as const, error: "Database unavailable." };
  // Registration-scoped sends (acceptance emails) have a natural stable identity —
  // "the acceptance email for this registration" — so they get real dedup
  // protection against double-submission. Manual sends (general broadcasts, test
  // emails) have no such identity; each click is intentionally a new, distinct
  // send, so they're never deduped against one another.
  const idempotencyKey = input.category === "ACCEPTANCE" && input.registrationId ? `accept-${input.registrationId}` : null;
  if (idempotencyKey) {
    const alreadySent = await db.select().from(emailLogs).where(and(eq(emailLogs.idempotencyKey, idempotencyKey), eq(emailLogs.status, "SENT"))).limit(1);
    if (alreadySent[0]) return { ok: true as const, id: alreadySent[0].providerMessageId ?? String(alreadySent[0].id) };
  }
  const logValues = { recipient: input.recipient, emailType: input.category, subject: input.subject, registrationId: input.registrationId, status: "SENDING" as const, sentBy: input.adminId, retryOf: input.retryOf, idempotencyKey };
  await db.insert(emailLogs).values(logValues);
  const log = await db.select().from(emailLogs).where(and(eq(emailLogs.recipient, input.recipient), eq(emailLogs.subject, input.subject))).orderBy(desc(emailLogs.id)).limit(1);
  const result = await sendEmail({ from, replyTo: config?.replyTo, to: [input.recipient], subject: input.subject, text: input.body, html: input.html, media: input.media });
  if (result.ok) { if (log[0]) await updateEmailLog(log[0].id, { status: "SENT", providerMessageId: result.id }); return { ok: true as const, id: result.id }; }
  if (log[0]) await updateEmailLog(log[0].id, { status: "FAILED", failureReason: result.error });
  await createNotification("Email delivery failed", `${input.category} email to ${input.recipient} failed: ${result.error}`, input.registrationId, "emailFailure");
  return result;
}

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(({ ctx }) => ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const options = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...options, maxAge: -1 }); return { success: true } as const; }),
    updateAccount: protectedProcedure.input(z.object({ name: z.string().trim().min(1).max(160), email: z.string().email().max(320) })).mutation(async ({ ctx, input }) => { const existing = await getDb().then(db => db ? db.select().from(users).where(and(eq(users.email, input.email.toLowerCase()), ne(users.id, ctx.user.id))).limit(1) : []); if (existing?.[0]) throw new Error("That email address is already in use"); return updateLocalAccount(ctx.user.id, { name: input.name, email: input.email.toLowerCase() }); }),
    changePassword: protectedProcedure.input(z.object({ currentPassword: z.string().min(8), newPassword: z.string().min(8).max(200) })).mutation(async ({ ctx, input }) => { if (!ctx.user.passwordHash || !verifyPassword(input.currentPassword, ctx.user.passwordHash)) throw new Error("Current password is incorrect"); await updateLocalAccount(ctx.user.id, { passwordHash: hashPassword(input.newPassword) }); return { success: true }; }),
  }),
  public: router({
    countries: publicProcedure.query(() => countries),
    levels: publicProcedure.input(z.object({ country: z.string() })).query(({ input }) => levels[input.country] ?? []),
    register: publicProcedure.input(z.object({ firstName: z.string().trim().min(1).max(120), lastName: z.string().trim().min(1).max(120), country: z.string(), countryCode: z.string(), whatsappNumber: z.string().min(5).max(40), classLevel: z.string(), school: z.string().trim().min(2).max(240), email: z.string().email().max(320) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Registration service is unavailable"); const validCountry = countries.find(c => c.name === input.country && c.code === input.countryCode); if (!validCountry || !(levels[input.country] ?? []).includes(input.classLevel)) throw new Error("Please check your country and class selection."); const digits = input.whatsappNumber.replace(/\D/g, ""); const normalized = input.countryCode + digits.replace(/^0+/, ""); try { await db.insert(registrations).values({ ...input, whatsappNumber: digits, normalizedWhatsapp: normalized, status: "PENDING" }); const inserted = await db.select({ id: registrations.id }).from(registrations).where(eq(registrations.normalizedWhatsapp, normalized)).orderBy(desc(registrations.id)).limit(1); await createNotification("New registration received", `New registration received from ${input.firstName} ${input.lastName}.`, inserted[0]?.id, "newRegistration"); return { success: true }; } catch (error: any) { if (String(error?.message ?? error).toLowerCase().includes("duplicate")) throw new Error("A registration with these contact details already exists."); throw new Error("We couldn't save your registration. Please try again."); } }),
  }),
  admin: router({
    stats: adminOnly.query(() => getStats()),
    registrations: adminOnly.input(z.object({ status: z.enum(["PENDING", "ACCEPTED", "REJECTED"]).optional(), search: z.string().optional() })).query(({ input }) => listRegistrations(input)),
    registration: adminOnly.input(z.object({ id: z.number() })).query(({ input }) => getRegistration(input.id)),
    deleteRegistration: adminOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const deleted = await deleteRegistration(input.id); if (!deleted) throw new Error("Registration not found."); await createAudit("Permanently deleted registration", ctx.user.id, undefined); return { success: true as const }; }),
    updateStatus: adminOnly.input(z.object({ id: z.number(), status: z.enum(["ACCEPTED", "REJECTED"]), reason: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const current = await getRegistration(input.id); if (!current) throw new Error("Registration not found"); if (current.status !== "PENDING") throw new Error("This request has already been reviewed."); await db.update(registrations).set({ status: input.status, reviewedAt: new Date(), reviewedBy: ctx.user.id, rejectionReason: input.reason ?? null }).where(and(eq(registrations.id, input.id), eq(registrations.status, "PENDING"))); await createAudit(`Registration ${input.status.toLowerCase()}`, ctx.user.id, input.id); if (input.status === "ACCEPTED") { await ensureDefaults(); const template = (await getConfig())?.template ?? ACCEPTANCE_DEFAULT; const rendered = htmlForTemplate(template, { firstName: current.firstName, lastName: current.lastName, fullName: `${current.firstName} ${current.lastName}`, school: current.school, classLevel: current.classLevel, country: current.country, email: current.email, whatsapp: `${current.countryCode} ${current.whatsappNumber}` }); await sendConfiguredEmail({ category: "ACCEPTANCE", recipient: current.email, subject: template.subject, body: rendered.body, html: rendered.html, adminId: ctx.user.id, registrationId: current.id, media: await getEmailMedia("id" in template ? template.id : undefined) }); } return { success: true }; }),
    retryEmail: adminOnly.input(z.object({ logId: z.number() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select().from(emailLogs).where(eq(emailLogs.id, input.logId)).limit(1); const failed = rows[0]; if (!failed || failed.status !== "FAILED") throw new Error("Only failed emails can be retried."); if (failed.registrationId) { const reg = await getRegistration(failed.registrationId); if (!reg) throw new Error("Registration not found."); const template = (await getConfig())?.template ?? ACCEPTANCE_DEFAULT; const rendered = htmlForTemplate(template, { firstName: reg.firstName, lastName: reg.lastName, fullName: `${reg.firstName} ${reg.lastName}`, school: reg.school, classLevel: reg.classLevel, country: reg.country, email: reg.email, whatsapp: `${reg.countryCode} ${reg.whatsappNumber}` }); return sendConfiguredEmail({ category: "ACCEPTANCE", recipient: reg.email, subject: template.subject, body: rendered.body, html: rendered.html, adminId: ctx.user.id, registrationId: reg.id, retryOf: failed.id, media: await getEmailMedia("id" in template ? template.id : undefined) }); } throw new Error("This email cannot be retried automatically."); }),
    config: adminOnly.query(async () => { await ensureDefaults(); const result = await getConfig(); if (result?.config) { const { gmailClientIdEncrypted, gmailClientSecretEncrypted, gmailRefreshTokenEncrypted, ...safeConfig } = result.config; return { ...result, config: { ...safeConfig, brevoConfigured: Boolean(ENV.brevoApiKey) } }; } return result; }),
    saveTemplate: adminOnly.input(z.object({ category: emailCategory.default("ACCEPTANCE"), subject: z.string().min(1).max(240), body: z.string().min(1), htmlBody: z.string().optional(), groupLink: z.string().url().optional().or(z.literal("")), channelLink: z.string().url().optional().or(z.literal("")) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await db.select().from(emailTemplates).where(eq(emailTemplates.category, input.category)).limit(1); const values = { ...input, category: input.category, updatedBy: ctx.user.id }; if (existing[0]) await db.update(emailTemplates).set(values).where(eq(emailTemplates.id, existing[0].id)); else await db.insert(emailTemplates).values(values); await createAudit(`Edited ${input.category.toLowerCase()} email template`, ctx.user.id); return { success: true }; }),
    restoreDefault: adminOnly.mutation(async ({ ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await db.select().from(emailTemplates).where(eq(emailTemplates.category, "ACCEPTANCE")).limit(1); const values = { ...ACCEPTANCE_DEFAULT, updatedBy: ctx.user.id }; if (existing[0]) await db.update(emailTemplates).set(values).where(eq(emailTemplates.id, existing[0].id)); else await db.insert(emailTemplates).values(values); await createAudit("Restored default acceptance email", ctx.user.id); return { success: true }; }),
    saveEmailConfig: adminOnly.input(z.object({ senderName: z.string().min(1).max(160), senderEmail: z.string().email(), replyTo: z.string().email().optional().or(z.literal("")), enabled: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await db.select().from(emailConfig).limit(1); const values = { senderName: input.senderName, senderEmail: input.senderEmail, replyTo: input.replyTo, enabled: input.enabled, updatedBy: ctx.user.id }; if (existing[0]) await db.update(emailConfig).set(values).where(eq(emailConfig.id, existing[0].id)); else await db.insert(emailConfig).values(values); await createAudit("Changed email sender configuration", ctx.user.id); return { success: true }; }),
    sendTestEmail: adminOnly.input(z.object({ recipient: z.string().email() })).mutation(async ({ ctx, input }) => { const result = await sendConfiguredEmail({ category: "SYSTEM_TEST", recipient: input.recipient, subject: "THE NEXT MIND email connection test", body: "This is a live connection test from THE NEXT MIND.", html: DEFAULT_HTML("<p>This is a live connection test from THE NEXT MIND.</p>"), adminId: ctx.user.id }); if (!result.ok) throw new Error(result.error); return { success: true, providerMessageId: result.id }; }),
    sendGeneralEmail: adminOnly.input(z.object({ recipients: z.array(z.string().email()).min(1).max(50), subject: z.string().min(1).max(240), body: z.string().min(1), htmlBody: z.string().optional(), mediaIds: z.array(z.number()).max(20).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const media = input.mediaIds?.length ? await db.select().from(emailMedia).where(inArray(emailMedia.id, input.mediaIds)) : []; const results = []; for (const recipient of Array.from(new Set(input.recipients))) { const result = await sendConfiguredEmail({ category: "GENERAL", recipient, subject: input.subject, body: input.body, html: input.htmlBody ?? DEFAULT_HTML(textToEmailHtml(input.body)), media, adminId: ctx.user.id }); results.push({ recipient, sent: result.ok, error: result.ok ? undefined : result.error }); } await createAudit(`Sent general email to ${results.length} recipients`, ctx.user.id); return { processed: results.length, sent: results.filter(r => r.sent).length, failed: results.filter(r => !r.sent).length, results }; }),
    uploadMedia: adminOnly.input(z.object({ filename: z.string().min(1).max(240), mimeType: z.string().regex(/^(image\/(png|jpeg|jpg|gif|webp)|video\/[a-z0-9.+-]+|audio\/[a-z0-9.+-]+|application\/(pdf|msword|vnd\.openxmlformats-officedocument\.wordprocessingml\.document|vnd\.ms-excel|vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet|vnd\.ms-powerpoint|vnd\.openxmlformats-officedocument\.presentationml\.presentation|zip)|text\/(plain|csv))$/), dataBase64: z.string().max(12_000_000), placement: z.enum(["INLINE", "ATTACHMENT"]), templateId: z.number().optional() })).mutation(async ({ ctx, input }) => { const raw = Buffer.from(input.dataBase64.replace(/^data:[^;]+;base64,/, ""), "base64"); if (raw.length > 8 * 1024 * 1024) throw new Error("Media files must be 8 MB or smaller."); const stored = await storagePut(`email-media/${ctx.user.id}/${Date.now()}-${input.filename.replace(/[^a-zA-Z0-9._-]/g, "-")}`, raw, input.mimeType); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const contentId = input.placement === "INLINE" ? `media-${crypto.randomUUID()}` : null; await db.insert(emailMedia).values({ templateId: input.templateId, fileKey: stored.key, fileUrl: stored.url, filename: input.filename, mimeType: input.mimeType, contentId, placement: input.placement, createdBy: ctx.user.id }); const created = await db.select().from(emailMedia).where(eq(emailMedia.fileKey, stored.key)).orderBy(desc(emailMedia.id)).limit(1); return { id: created[0]?.id, url: stored.url, filename: input.filename, mimeType: input.mimeType, contentId, placement: input.placement }; }),
    media: adminOnly.input(z.object({ templateId: z.number().optional() })).query(({ input }) => getEmailMedia(input.templateId)),
    logs: adminOnly.input(z.object({ limit: z.number().min(1).max(100).default(50) })).query(async ({ input }) => { const db = await getDb(); if (!db) return []; return db.select().from(emailLogs).orderBy(desc(emailLogs.createdAt)).limit(input.limit); }),
    notificationPreferences: adminOnly.query(async () => { const db = await getDb(); if (!db) return undefined; await ensureDefaults(); const rows = await db.select().from(notificationPreferences).limit(1); return rows[0]; }),
    saveNotificationPreferences: adminOnly.input(z.object({ masterEnabled: z.boolean(), newRegistration: z.boolean(), emailFailure: z.boolean(), adminEvents: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await db.select().from(notificationPreferences).limit(1); if (existing[0]) await db.update(notificationPreferences).set({ ...input, updatedBy: ctx.user.id }).where(eq(notificationPreferences.id, existing[0].id)); else await db.insert(notificationPreferences).values({ ...input, updatedBy: ctx.user.id }); await createAudit("Changed notification preferences", ctx.user.id); return { success: true }; }),
    notifications: adminOnly.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(notifications).orderBy(desc(notifications.createdAt)).limit(50); }),
    admins: adminOnly.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ id: users.id, name: users.name, email: users.email, loginMethod: users.loginMethod, createdAt: users.createdAt, lastSignedIn: users.lastSignedIn }).from(users).where(eq(users.role, "admin")).orderBy(desc(users.lastSignedIn)); }),
    dismissAdmin: adminOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (ctx.user.id === input.id) throw new Error("You cannot dismiss your own active admin account."); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ role: "user" }).where(and(eq(users.id, input.id), eq(users.role, "admin"))); await createAudit("Dismissed administrator", ctx.user.id); return { success: true as const }; }),
    createInvite: adminOnly.input(z.object({ origin: z.string().url(), hours: z.number().min(1).max(168).default(24) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const raw = crypto.randomBytes(32).toString("hex"); const hash = crypto.createHash("sha256").update(raw).digest("hex"); await db.insert(adminInvites).values({ tokenHash: hash, createdBy: ctx.user.id, expiresAt: new Date(Date.now() + input.hours * 3600000) }); await createAudit("Generated admin invite", ctx.user.id); return { url: `${input.origin}/auth/signup/${raw}` }; }),
    invites: adminOnly.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ id: adminInvites.id, createdAt: adminInvites.createdAt, expiresAt: adminInvites.expiresAt, usedAt: adminInvites.usedAt, revokedAt: adminInvites.revokedAt }).from(adminInvites).orderBy(desc(adminInvites.createdAt)).limit(100); }),
    revokeInvite: adminOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(adminInvites).set({ revokedAt: new Date() }).where(and(eq(adminInvites.id, input.id), isNull(adminInvites.usedAt), isNull(adminInvites.revokedAt))); await createAudit("Revoked admin invite", ctx.user.id); return { success: true as const }; }),
    deleteInvite: adminOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(adminInvites).where(eq(adminInvites.id, input.id)); await createAudit("Deleted admin invite", ctx.user.id); return { success: true as const }; }),
    consumeInvite: protectedProcedure.input(z.object({ token: z.string().min(32).max(128) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const hash = crypto.createHash("sha256").update(input.token).digest("hex"); const rows = await db.select().from(adminInvites).where(and(eq(adminInvites.tokenHash, hash), isNull(adminInvites.usedAt), isNull(adminInvites.revokedAt), gt(adminInvites.expiresAt, new Date()))).limit(1); if (!rows[0]) throw new Error("This invitation is invalid, expired, revoked, or already used."); await db.update(adminInvites).set({ usedAt: new Date(), usedBy: ctx.user.id }).where(eq(adminInvites.id, rows[0].id)); await db.update(users).set({ role: "admin" }).where(eq(users.id, ctx.user.id)); await createAudit("Joined as admin using invite", ctx.user.id); return { success: true }; }),
  }),
});
export type AppRouter = typeof appRouter;
